plugins = []
headers = []
redirects = []

[dev]
command = "vite"
port = 3000.0
publish = "dist"

[functions]

[functions."*"]

[build]
publish = "C:\\My Projects\\finprojects\\GrowWithUs\\growithus_ui\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\My Projects\\finprojects\\GrowWithUs\\growithus_ui"
command = "npm install && npm run build"
force = "true"
ignore = "false"

[build.environment]
NODE_VERSION = "18"
CI = "true"
NETLIFY_BUILD_SKIP = "false"

[build.processing]
skip_processing = false

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]