name: Node Backend Deploy

on:
  push:
    paths:
      - 'growithus_api/**'
    branches:
      - '*release*'

  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'Branch to deploy'
        required: true
        default: 'release'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.deploy_branch || github.ref_name }}
          fetch-depth: 0

      - name: Setup Node 24
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Build
